### ISSUE TITLE
No crea el pedido

### ISSUE THREAD

**Issue by blueandweb** [RubenQuintela/cecamodule#4]
Hola a todos, antes de nada agradecer el esfuero por crear este modulo. Estoy haciendo pruebas y me da el siguiente error: me realiza el pago correctamente y se refleja en el tpv virtual pero no me crea el nuevo pedido en prestashop, estoy utilizando la version 7.1.16.
Ya he modificado el archivo validator.php.
¿Sabeis porque puede fallar?
Gracias, un saludo.

**Comment by 46dude** [comment]
A mi me pasó pero es algo de configuración muy sencillo de arreglar. Algo
que viene expresamente en las instrucciones del módulo y ahora no recuerdo.
Revisa las instrucciones detenidamente, yo lo arreglé así

**Comment by blueandweb** [comment]
Muchas gracias, voy a revisarlo a ver si lo soluciono. 😄

**Comment by dfragac** [comment]
Puede ser por varios motivos:

1. Comprueba los "carritos" de prestashop, si está ahí y ya está pagado es porque en la configuración de CECA (en la intranet de ceca, no en el prestashop) no está configurada la "URL online OK". La configuras (sudominio.com/modules/cecamodule/validation.php) y ya debería funcionar.
2. Si te da un error en el pago después del punto 1 puede ser un problema con el validation.php (tengo un fork en mi repo con el cambio realizado).
3. Si te da un error de validación puede ser porque CECA sólo valida con TLS 1.0 o TLS 1.1 si tienes SSL. Compruébalo y activa esas versiones.

**Comment by blueandweb** [comment]
Muchas gracias, siguendo tus consejos ya parece que va todo ok :) voy a seguir haciendo pruebas, 
Aprovecho para preguntaros si sabeis porque al realizar el pago me lanza un mensaje que dice:

La información que ha introducido en esta página se enviará a través de una conexión no segura y podría ser leída por terceros.
¿Está seguro de que quiere enviar esta información?

Es por el modulo, es por que mi ssl es gratuito, por estar en modo pruebas, o es que me falta configurar algo???

**Comment by dfragac** [comment]
Tu página tiene certificado SSL? (HTTP o HTTPS?)
Puede ser por eso, si no tienes el HTTPS activo indica que el formulario se mandará en plano.

**Comment by 46dude** [comment]
La comunicación con el tpv virtual debería de ser encriptada (https) otra
cosa es que tu web tenga habilitado un certificado o no. No hay problema en
que sea gratuito, es idéntico a los de pago. Tienes que mirar si cuando
comunica con la pasarela la web que carga es https. En caso afirmativo no
debería de dar ese error, yo probaría con otros navegadores. Si tienes
habilitado ssl ya en tu web tampoco debería dar ese error. Es raro pero
investiga a dónde conecta la web cuando da ese error, tendría que ser a
alguna página http.

**Comment by blueandweb** [comment]
Muchas gracias, :)

**Comment by blueandweb** [comment]
Doy por cerrado y solucionado, gracias a todos por la ayuda.

**Comment by MartinCriado** [comment]
Buenas tardes!

No consigo que me haga la comunicación ok entre el entorno de pruebas y prestashop. ¿Como lo solucionaste @blueandweb?

**Comment by dfragac** [comment]
¿Qué error te da? ¿Tienes bien configurados los parámetros del plugin? ¿Tu web es https o no?

**Comment by MartinCriado** [comment]
Si están correctos los parámetros porque hace la conexión, el caso es que cuando meto una tarjeta para pruebas (ficticia) si tengo activo dentro del panel de mi tpv que haga la comunicación entre tpv y prestashop y viceversa. 

El tpv me saca un error de comunicación.

Mi web es https, y así lo configuré en el panel de control de mi tpv.

**Comment by dfragac** [comment]
OK, activa en la intranet de CECA el email de desarrollo y te enviará un mail con el error. ¿Qué código de error te sale? ¿La web está "en desarrollo" o la tienes abierta?

**Comment by MartinCriado** [comment]
La web está en desarrollo aún, no está activa.

El mail de error es éste:

Hola,

Se ha producido un error de comunicacion on-line en su comercio 081642928 en la operacion 000000000079.

La comunicacion on-line es utilizada por los comercios que necesita que las operaciones de COMPRA realizadas por sus clientes le sean comunicadas en el momento de producirse. Esta url se encuentra en el apartado de configuracion de la consola del TPV Virtual.

La URL configurada para su comercio es: https://www.decoraconcajas.com/modules/cecamodule/validation.php.

La respuesta obtenida es:

https://www.decoraconcajas.com/modules/cecamodule/validation.php: Error http 503

Para que la operacion sea correcta esperamos que en la respuesta se encuentra la cadena $*$OKY$*$.

Asegurese que esta utilizando uno de los puertos estandar como es el 80 y el 443. En caso contrario el firewall bloqueara la llamada

Si la url es por htts y no hay respuesta o existe un time out es posible que la entidad certificadora no la tengamos dada de alta. Envie un correo a tpv@ceca.es indicando en el asunto "revision entidad certificadora en pruebas" y edjunte la url. Le responderemos lo antes posible.

Para mas informacion sobre el funcionamiento de la comunicacion online, haga clic en el siguiente enlace y consulte el apartado 6.

https://comercios.ceca.es/docs_constpv/img/manual_comercios.pdf

Saludos.

**Comment by dfragac** [comment]
Cuando la web está en "en construcción" no funciona el TPV. Prueba a ponerla online un segundo, haz el pago y luego la cierras, debería funcionar.

**Comment by MartinCriado** [comment]
Funcionó, ¿Cómo no había caído en eso? Al estar en mantenimiento tenía bloqueada la comunicación y el tpv no podía enviarle el ok de la operación.

Un millón de gracias @dfragac ;)

**Comment by dfragac** [comment]
👍 Me alegro. Un saludo! :-)
